### ISSUE TITLE
Reuse Established Connection

### ISSUE THREAD

**Issue by mblauser** [barleybobs/ecowater-softener#1]
Currently each function to query status (e.g. saltLevel, saltLevelPercent, waterUnits) makes a call to _get() and subsequently establishes a new server connection/login.  This not only makes querying multiple server status values time consuming, the vendor may identify this resource strain and take decisive action.

Is it possible to re-use an already established server connection to query every X number of seconds for updated status values, or is the connection forcibly closed after every server query?  

Alternatively, a more conservative server resources approach might be to create class variables for each status value of interest, updating ALL of the class variables via a single call to _get() once they are determined stale.  The server call to "/Dashboard/UpdateFrequentData" already returns all possible status values.  Use this single call to update the class variables.

Perhaps 'staleness' could be given by a user defined value?  Function calls for each status value of interest (e.g. saltLevel, saltLevelPercent) would simply return the current value of the class variable (if not stale, else obtain new values from server).

Thank you for the effort given to this and I greatly look forward to a future HomeAssistant integration.

**Comment by barleybobs** [comment]
> @mblauser Currently each function to query status (e.g. saltLevel, saltLevelPercent, waterUnits) makes a call to _get() and subsequently establishes a new server connection/login.

What I can do is add a function that returns all of the data as a dictionary so all you need to do is pull the correct data with the right keys. This would only use one request. Would that work for you?

**Comment by mblauser** [comment]
> What I can do is add a function that returns all of the data as a dictionary so all you need to do is pull the correct data with the right keys. This would only use one request. Would that work for you?

That seems much more efficient.  

I recently discovered your implementation for HACS which similarly employs a dictionary for attributes. Thank you for your efforts toward this development.

**Comment by barleybobs** [comment]
> @mblauser I recently discovered your implementation for HACS which similarly employs a dictionary for attributes. Thank you for your efforts toward this development.

Thanks for your kind words.

Solved in commit fa9dc39 by the introduction of the getData() function.

Thanks 👍
